# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    view:
        view_response_listener:  true
    routing_loader:
        default_format: json
        include_format: false
    body_converter:
        enabled: true
        validate: true
    versioning: true
    exception:
        enabled: false
        exception_controller: 'fos_rest.exception.controller:showAction'
